### ISSUE TITLE
Non-default symlink behaviour

### ISSUE THREAD

**Issue by me-and** [egor-tensin/setup-cygwin#1]
Hi,

I'm the Cygwin maintainer for Git, and I'm trying to set up GitHub Actions to do CI-style builds, rather than my current manual build process, and for that I've been playing with this action. Unfortunately, this action currently causes the `cygport unpack` build stage to fail for the Git project, because it sets `CYGWIN=winsymlinks:nativestrict`. See https://github.com/me-and/Cygwin-Git/runs/1601065913 for an example of the failure.

I've been experimenting over at me-and/setup-cygwin@7119423 and confirmed that removing that symlinking behaviour gets the builds working as expected for my use case.

I can see three obvious-to-me approaches, all of which I'm happy with, but I'd like to know what you'd prefer before I submit a PR:

1. Add a new "CYGWINENV" input that defaults to an empty string, and sets the `CYGWIN` environment variable to whatever it's configured with. This would not be back-compatible, but seems most likely to cause minimal surprise to people who are expecting Cygwin's default behaviour except when they've deliberately asked for something else.

2. Add a new "CYGWINENV" input that defaults to `winsymlinks:nativestrict` but otherwise works as per the previous point. In my opinion this would violate the principle of least surprise, but would not require a backwards-incompatible change.

3. Don't make any changes, in which case I'll maintain my fork, probably taking option 1 above.

If you let me know which you prefer, I'll submit a PR with the relevant changes :)

**Comment by egor-tensin** [comment]
I prefer option #1, but I suggest the parameter to be named `env` in line with the existing `platform`, `install-dir` and `packages`. I'll simply release version 2 then. To be honest, I only set the `CYGWIN` variable because I wanted an easy way to detect that this action has been run in my jobs, and `winsymlinks:nativestrict` is something I use locally.

**Comment by me-and** [comment]
That makes sense! I'll spin up a pull request shortly :)

And I'd figured that more-or-less exactly that was what was going on with the files, yes. Even with that restriction, I'm finding it an incredibly useful starting point for setting up the GitHub Actions! Thank you!

**Comment by egor-tensin** [comment]
v2 now behaves like this, which is more sensible compared to v1.
