### ISSUE TITLE
zlib-devel and perl-YAML-Tiny Cygwin packages fail to install

### ISSUE THREAD

**Issue by me-and** [egor-tensin/setup-cygwin#3]
I _suspect_ this is a bug with Chocolatey, but I'm not managing to work out what's going on well enough, or to reproduce the problem without using this GitHub Action, so I'm reporting this here in the hope we can work out what's going on.

Clearest example of the problem is at https://github.com/me-and/Cygwin-Git/actions/runs/441220070: I've used the action in this repository to install zlib-devel in the "Install Cygwin" job. However if you look at the cygcheck.out file, which is generated in the "Generate cygcheck output" job and stored as an artefact in "cyg-install-logs", you can see the package isn't listed in the set of installed packages.

Looking through the installation logs, everything seems to be reporting itself as successful, and in particular the logs from Chocolatey seem to show it attempting to install the zlib-devel package, running the Cygwin installer, which doesn't seem to meaningfully do anything, and reports success.

**Comment by egor-tensin** [comment]
It works for me, see e.g. https://github.com/egor-tensin/setup-cygwin/runs/1605133267?check_suite_focus=true (only the "Set up Cygwin" step matters here).

Try not using the multiline YAML strings as the `packages` parameter value. Do this:

        with:
          platform: ${{ matrix.platform }}
          packages: zlib-devel

instead of 

        with:
          platform: ${{ matrix.platform }}
          packages: >
            zlib-devel

**Comment by me-and** [comment]
I have to admit, I really didn't expect that to work; I was convinced the two bits of syntax were identical. But it very clearly does. I need to do some more digging to understand _why_ it works, but I can go do that.

Thank you!

**Comment by egor-tensin** [comment]
@me-and _Maybe_ something like this would work, if you want to keep one package name per line:

        with:
          packages: >-
            package1
            package2

You can see https://yaml-multiline.info/ for the crazy multiline-string rules in YAML.
