### ISSUE TITLE
cygwin for building python extension

### ISSUE THREAD

**Issue by pdobsan** [egor-tensin/setup-cygwin#7]
I would like to build a Python/C extension module for windows using cygwin and Gitbub actions.
Additionally to `python3` there are only two things I need, `gnu make` and `gcc`. 

As an initial step I created a [minimal workflow](https://github.com/pdobsan/pynauty/blob/main/.github/workflows/cygwin.yml). That [fails](https://github.com/pdobsan/pynauty/actions/runs/686193776) miserably, after countless iterations.

 Could you please help me with this problem, thanks.

**Comment by egor-tensin** [comment]
I see that the latest run of the "Build in Cygwin" workflow ended with the following error:

> egor-tensin/setup-cygwin@v3 is not allowed to be used in pdobsan/pynauty. Actions in this workflow must be: within a repository owned by pdobsan or created by GitHub.

I've never seen this one before. After a bit of googling, it seems like it can appear after setting your Actions policy to only allow local actions to be run (in the "Actions" tab in repository's settings). Could you please check if this is your case?
![image](https://user-images.githubusercontent.com/355889/112600144-ddbabd80-8e21-11eb-9a5a-0043faf9ca95.png)

**Comment by pdobsan** [comment]
Oops, I forgot about adding your action to the allowed actions. Thank you for the pointer, that solved the problem. Also many thanks for your `setup-cygwin` action!
